//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonDK
    {
        public int MaHD { get; set; }
        public int MaSim { get; set; }
        public System.DateTime NgayDK { get; set; }
        public decimal ChiPhi { get; set; }
        public int MaKH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Sim Sim { get; set; }
    }
}
