//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiCuoc
    {
        public int STT { get; set; }
        public string MaLoaiCuoc { get; set; }
        public System.TimeSpan TG_BatDau { get; set; }
        public System.TimeSpan TG_KetThuc { get; set; }
        public System.DateTime NgayApdung { get; set; }
        public decimal GiaCuoc { get; set; }
        public bool Status { get; set; }
    }
}
