//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class QLCuocDTEntities : DbContext
{
    public QLCuocDTEntities()
        : base("name=QLCuocDTEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<CuocGoi> CuocGois { get; set; }
    public virtual DbSet<HoaDonDK> HoaDonDKs { get; set; }
    public virtual DbSet<HoaDonThanhToan> HoaDonThanhToans { get; set; }
    public virtual DbSet<KhachHang> KhachHangs { get; set; }
    public virtual DbSet<LoaiCuoc> LoaiCuocs { get; set; }
    public virtual DbSet<Sim> Sims { get; set; }
    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
}
