//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CuocGoi
{
    public int MaCuocGoi { get; set; }
    public int MaSim { get; set; }
    public System.DateTime TG_BatDau { get; set; }
    public System.DateTime TG_KetThuc { get; set; }
    public int SoPhutSD { get; set; }
    public bool trangthai { get; set; }
    public Nullable<decimal> PhiCuocGoi { get; set; }

    public virtual Sim Sim { get; set; }
}

public partial class HoaDonDK
{
    public int MaHD { get; set; }
    public int MaSim { get; set; }
    public System.DateTime NgayDK { get; set; }
    public decimal ChiPhi { get; set; }
    public int MaKH { get; set; }

    public virtual KhachHang KhachHang { get; set; }
    public virtual Sim Sim { get; set; }
}

public partial class HoaDonThanhToan
{
    public int MaHD { get; set; }
    public int MaKH { get; set; }
    public int MaSim { get; set; }
    public decimal CuocThueBao { get; set; }
    public System.DateTime NgayHD { get; set; }
    public bool ThanhToan { get; set; }
    public decimal ThanhTien { get; set; }
    public bool Status { get; set; }

    public virtual KhachHang KhachHang { get; set; }
    public virtual Sim Sim { get; set; }
}

public partial class KhachHang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KhachHang()
    {
        this.HoaDonDKs = new HashSet<HoaDonDK>();
        this.HoaDonThanhToans = new HashSet<HoaDonThanhToan>();
    }

    public int MaKH { get; set; }
    public string TenKH { get; set; }
    public string CMND { get; set; }
    public string NgheNghiep { get; set; }
    public string DiaChi { get; set; }
    public bool Status { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoaDonDK> HoaDonDKs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoaDonThanhToan> HoaDonThanhToans { get; set; }
}

public partial class LoaiCuoc
{
    public int STT { get; set; }
    public string MaLoaiCuoc { get; set; }
    public System.TimeSpan TG_BatDau { get; set; }
    public System.TimeSpan TG_KetThuc { get; set; }
    public System.DateTime NgayApdung { get; set; }
    public decimal GiaCuoc { get; set; }
    public bool Status { get; set; }
}

public partial class Sim
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sim()
    {
        this.CuocGois = new HashSet<CuocGoi>();
        this.HoaDonDKs = new HashSet<HoaDonDK>();
        this.HoaDonThanhToans = new HashSet<HoaDonThanhToan>();
    }

    public int MaSim { get; set; }
    public string SoSim { get; set; }
    public bool Status { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CuocGoi> CuocGois { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoaDonDK> HoaDonDKs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoaDonThanhToan> HoaDonThanhToans { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
