CREATE DATABASE QLVeSo
GO
--
USE QLVeSo
GO

--TABLE--
CREATE TABLE DaiLy
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	Ten NVARCHAR(100),
	DiaChi NVARCHAR(200),
	DienThoai VARCHAR(12),
	TinhTrang NVARCHAR(20)
)

CREATE TABLE LoaiVeSo
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Ma VARCHAR(10) NOT NULL,
	Tinh NVARCHAR(50),
	TinhTrang NVARCHAR(20)
)

CREATE TABLE DangKy
(
	IdDaiLy UNIQUEIDENTIFIER NOT NULL,
	IdVeSo UNIQUEIDENTIFIER NOT NULL,
	NgayDangKy DATE,
	SoLuong INT
)

CREATE TABLE PhanPhoi
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	IdDaiLy UNIQUEIDENTIFIER NOT NULL,
	IdVeSo UNIQUEIDENTIFIER NOT NULL,
	Ngay DATE,
	SoLuongGiao INT,
	SoLuongBan INT
)

--CONSTRAINT--
ALTER TABLE DangKy
	ADD
		CONSTRAINT FK_DangKy_LoaiVeSo_MaVeSo FOREIGN KEY (IdVeSo) REFERENCES LoaiVeSo(Id),
		CONSTRAINT FK_DangKy_DaiLy_MaDaiLy FOREIGN KEY (IdDaiLy) REFERENCES DaiLy(Id),
		CONSTRAINT PK_DangKy_MaDaiLy_MaVeSo PRIMARY KEY (IdDaiLy, IdVeSo)
GO

ALTER TABLE PhanPhoi
	ADD
		CONSTRAINT FK_PhanPhoi_LoaiVeSo_MaVeSo FOREIGN KEY (IdVeSo) REFERENCES LoaiVeSo(Id),
		CONSTRAINT FK_PhanPhoi_DaiLy_MaDaiLy FOREIGN KEY (IdDaiLy) REFERENCES DaiLy(Id)
